# Jekyll configuration for GitHub Pages
title: EasyBreezy Fashion Store
description: Tampil Keren Harga Terjangkau - Fashion Store
baseurl: "" # Leave empty for GitHub Pages
url: "" # GitHub Pages will set this automatically

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-primer

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - "*.log"

# GitHub Pages specific settings
safe: true
incremental: false
lsi: false

# Disable Jekyll processing for HTML files
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Keep original file structure
permalink: pretty